FROM mogria/rtsh-srv:latest

WORKDIR /gamesrv
RUN easy_install nose

VOLUME ["/gamesrv"]

# run nosetests with the following options:
# - consider file which have the executable flag set
# - don't buffer stdout
ENTRYPOINT ["nosetests", "--exe"]
