FROM mogria/rtsh-srv:latest

WORKDIR /gamesrv
ADD setup.py /gamesrv
RUN ls -al /gamesrv
RUN python setup.py develop
RUN easy_install nose

VOLUME ["/gamesrv"]

# run nosetests with the following options:
# - consider file which have the executable flag set
# - don't buffer stdout
ENTRYPOINT ["nosetests", "--exe", "--nocapture"]
