#!/bin/bash

# ***************************************
# args are:
# 1: unit type (swordFighter, ..)
# 2: x coordinate
# 3: y coordinate
# ***************************************

source "$(dirname "${BASH_SOURCE[0]}")/../lib/gameobjects.sh"

if [ "$#" -ne 3 ]; then
    echo "usage: $0 unitType ($UNIT_TYPES) x y ";
    exit 0
fi

CMD_NAME=$0
ARGS=$@
UNIT_TYPE=$1
X=$2
Y=$3

echo "you cheater you .."
echo "i am '" $CMD_NAME "' and i was called with the args: '" $ARGS "'"

new_unit $UNIT_TYPE > "/world/$X/$Y/units/unit-$UNIT_TYPE.json"



