#!/bin/bash

# ***************************************
# args are:
# 1: unit type (swordfighter, ..)
# 2: x coordinate
# 3: y coordinate
# ***************************************


containsElement() {
    local e
    for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
    return 1
}

set_attr_str() {
    echo "\"$1\": \"$2\","
#    jq --arg attr "$2" ".$1 = \$attr"
}

new() {
    if [ "$#" -ne 1 ]; then
        return 1
    fi

    CLASSES=( "tile"  "world" "unit" "building" )
    if containsElement "$1" "${CLASSES[@]}"; then
        set_attr_str "class" "$1"
        return 0
    fi
    return 1
}

new_unit() {
    if containsElement "$UNIT_TYPE" "${UNIT_TYPES[@]}"; then
        echo "{"
        new "unit"
        set_attr_str "type" "$UNIT_TYPE"
        echo "}"
        return 0
    fi
    return 1
}


UNIT_TYPES=("swordfighter")
if [ "$#" -ne 3 ]; then
    echo "usage: $0 unitType ($UNIT_TYPES) x y ";
    exit 0
fi

CMD_NAME=$0
ARGS=$@
UNIT_TYPE=$1
X=$2
Y=$3

echo "you cheater you .."
echo "i am '" $CMD_NAME "' and i was called with the args: '" $ARGS "'"

new_unit $UNIT_TYPE > "/world/$X/$Y/unit-$UNIT_TYPE.json"



