#!/bin/bash
# ***************************************
# args are:
# 1: x coordinate
# 2: y coordinate
# 3: unit file
# ***************************************

unit_get_coordinates() {
    local unitfile="$1"
    cat | jq [
}
